{
  "formatVersion": "1.1",
  "component": {
    "group": "com.billy.android",
    "module": "cc-register",
    "version": "1.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cc-register-1.1.3-SNAPSHOT.jar",
          "url": "cc-register-1.1.3-SNAPSHOT.jar",
          "size": 144855,
          "sha512": "30cdfcf8a1af2abf8ff03d7d62bf7c8e7ceb69f7c1e4c97b96c8dfc181f6acf4af6c7343f11fc664904cd912db850f306059547a11331fce6330661de67d6a34",
          "sha256": "3d18afa6bd28e9b7d738edf1b78ff6bdbe525c6bed06943bdb51479b6c8d6ac4",
          "sha1": "6fcff5472b42cd1f201a691ab7c8924ba9ff11f1",
          "md5": "5de51fa8b9bcb25ea66c4fc1ef510e5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "cc-register-1.1.3-SNAPSHOT.jar",
          "url": "cc-register-1.1.3-SNAPSHOT.jar",
          "size": 144855,
          "sha512": "30cdfcf8a1af2abf8ff03d7d62bf7c8e7ceb69f7c1e4c97b96c8dfc181f6acf4af6c7343f11fc664904cd912db850f306059547a11331fce6330661de67d6a34",
          "sha256": "3d18afa6bd28e9b7d738edf1b78ff6bdbe525c6bed06943bdb51479b6c8d6ac4",
          "sha1": "6fcff5472b42cd1f201a691ab7c8924ba9ff11f1",
          "md5": "5de51fa8b9bcb25ea66c4fc1ef510e5b"
        }
      ]
    }
  ]
}
